# Generated by Django 4.2.29 on 2026-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_admindeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindeposit',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=12),
        ),
    ]
