# Generated by Django 4.2.29 on 2026-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_admindeposit_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
